{% set name = "tico" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 8f103404339ed93f832c081cc69f63d933ed59abe103c0d5eff1d83cfc016cb2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - versioneer
  run:
    - python >=3.10
    - pytorch
    - networkx
    - smee-base

test:
  imports:
    - tico

about:
  home: https://github.com/SimonBoothroyd/tico
  summary: 'Torch-based internal coordinate geometry optimization'
  description: |
    A framework that provides utilities for optimizing the geometry of molecules in
    internal coordinates, subject to constraints.
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE-3RD-PARTY
  doc_url: https://simonboothroyd.github.io/tico/latest/
  dev_url: https://github.com/SimonBoothroyd/tico

extra:
  recipe-maintainers:
    - SimonBoothroyd
